window.IHFallback = {
  categorias: [
    { id: "innovacion", nombre: "Innovación y emprendimiento" },
    { id: "sostenibilidad", nombre: "Sostenibilidad" },
    { id: "educacion", nombre: "Educación" },
    { id: "salud", nombre: "Salud y bienestar" },
    { id: "tecnologia", nombre: "Tecnología" },
    { id: "comunidad", nombre: "Comunidad" }
  ],
  iniciativas: [
    { id: "ihu-001", titulo: "Mapa de espacios accesibles", tipo: "Idea", resumen: "Un mapa colaborativo para ubicar rutas y espacios accesibles en el campus.", descripcion: "Crear un mapa actualizado por la comunidad con rutas, rampas, ascensores y servicios accesibles.", problema: "La información de accesibilidad está dispersa.", beneficiarios: "Estudiantes, docentes y visitantes.", categoria: "Comunidad", propietario: "Lucía Fernández", competencias: ["Diseño UX", "Desarrollo web", "Accesibilidad"], estado: "En búsqueda de equipo", visibilidad: "Pública", miembros: ["Lucía Fernández"], participantesEstimados: 5, etiquetas: ["campus", "accesibilidad"] },
    { id: "ihu-002", titulo: "Huerta inteligente universitaria", tipo: "Reto", resumen: "Diseñar una huerta de bajo consumo de agua con monitoreo básico de humedad.", descripcion: "Prototipo de huerta universitaria con cultivo sostenible y sensores accesibles.", problema: "El cultivo requiere riego y seguimiento manual.", beneficiarios: "Comunidad estudiantil y mantenimiento.", categoria: "Sostenibilidad", propietario: "Andrés Mora", competencias: ["IoT", "Agricultura urbana", "Electrónica"], estado: "Abierta", visibilidad: "Comunidad", miembros: ["Andrés Mora", "Sofía Rojas"], participantesEstimados: 6, etiquetas: ["ambiente", "iot"] },
    { id: "ihu-003", titulo: "Tutorías entre pares", tipo: "Necesidad", resumen: "Conectar a estudiantes que buscan apoyo académico con compañeros tutores.", descripcion: "Red de tutorías entre estudiantes con horarios y materiales compartidos.", problema: "Falta apoyo académico oportuno.", beneficiarios: "Estudiantes de primeros cursos.", categoria: "Educación", propietario: "María Chaves", competencias: ["Docencia", "Organización", "Comunicación"], estado: "En búsqueda de equipo", visibilidad: "Pública", miembros: ["María Chaves"], participantesEstimados: 8, etiquetas: ["aprendizaje", "tutorías"] },
    { id: "ihu-004", titulo: "Pausa activa", tipo: "Idea", resumen: "Microactividades para promover pausas saludables durante jornadas de estudio.", descripcion: "Ejercicios breves, recordatorios y recomendaciones de bienestar.", problema: "Las jornadas largas afectan concentración y bienestar.", beneficiarios: "Estudiantes y docentes.", categoria: "Salud y bienestar", propietario: "Diego Salas", competencias: ["Salud", "Diseño de contenido", "Desarrollo web"], estado: "Abierta", visibilidad: "Pública", miembros: ["Diego Salas", "Valeria León"], participantesEstimados: 4, etiquetas: ["bienestar", "hábitos"] },
    { id: "ihu-005", titulo: "Banco de intercambio de libros", tipo: "Necesidad", resumen: "Facilitar el préstamo e intercambio de libros entre estudiantes.", descripcion: "Catálogo comunitario para registrar libros y coordinar préstamos.", problema: "El costo de materiales limita su acceso.", beneficiarios: "Estudiantes de todos los programas.", categoria: "Educación", propietario: "José Vega", competencias: ["Desarrollo web", "Bases de datos", "Gestión de comunidad"], estado: "Abierta", visibilidad: "Institucional", miembros: ["José Vega"], participantesEstimados: 5, etiquetas: ["libros", "intercambio"] },
    { id: "ihu-006", titulo: "Clasificador de residuos", tipo: "Reto", resumen: "Mejorar la separación de residuos con señalización y datos de uso.", descripcion: "Diseño de señalización y medición de participación en puntos de reciclaje.", problema: "Los materiales reciclables se mezclan.", beneficiarios: "Comunidad universitaria.", categoria: "Sostenibilidad", propietario: "Camila Arias", competencias: ["Diseño gráfico", "Análisis de datos", "Sostenibilidad"], estado: "En búsqueda de equipo", visibilidad: "Comunidad", miembros: ["Camila Arias"], participantesEstimados: 5, etiquetas: ["reciclaje", "ambiente"] },
    { id: "ihu-007", titulo: "Asistente de orientación académica", tipo: "Idea", resumen: "Prototipo conversacional para encontrar recursos y contactos universitarios.", descripcion: "Prototipo que organiza preguntas frecuentes y dirige a recursos institucionales.", problema: "Cuesta encontrar el servicio universitario correcto.", beneficiarios: "Estudiantes nuevos y visitantes.", categoria: "Tecnología", propietario: "Pablo Jiménez", competencias: ["Inteligencia artificial", "Diseño UX", "Accesibilidad"], estado: "Abierta", visibilidad: "Restringida", miembros: ["Pablo Jiménez", "Equipo de orientación"], participantesEstimados: 4, etiquetas: ["orientación", "prototipo"] },
    { id: "ihu-008", titulo: "Directorio de espacios de estudio", tipo: "Necesidad", resumen: "Reunir horarios, capacidad y servicios de los espacios de estudio.", descripcion: "Directorio para comparar espacios de estudio según necesidades.", problema: "No hay un lugar para comparar espacios disponibles.", beneficiarios: "Estudiantes.", categoria: "Innovación y emprendimiento", propietario: "Fernanda Ruiz", competencias: ["Desarrollo web", "Investigación UX", "Gestión de datos"], estado: "En búsqueda de equipo", visibilidad: "Pública", miembros: ["Fernanda Ruiz"], participantesEstimados: 5, etiquetas: ["campus", "estudio"] }
  ]
};
